AWSTemplateFormatVersion: '2010-09-09'
Description: creating new ec2

Resources:
  WebServerSecurity:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: ssh port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Warning: Allows access from anywhere. Best practice is to limit to your IP.

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-051a31ab2f4d498f5
      KeyName: aus
      # Attach the Security Group created above
      SecurityGroups:
        - !Ref WebServerSecurity
      # Example: Latest Amazon Linux 2 AMI for us-east-1
      Tags:
        - Key: Name
          Value: new-cicd-sys-demo